print("")
print("LETS PLAY SEEKER! :D")
print("")
start = input("PRESS ANY KEY TO START")
print("")
print("HERE IS THE BOARD")
print("")
print("  1  2  3  4  5 ")
print("1[ ][ ][ ][ ][ ]")
print("2[ ][ ][ ][ ][ ]")
print("3[ ][ ][ ][ ][ ]")
print("4[ ][ ][ ][ ][ ]")
print("5[ ][ ][ ][ ][ ]")
print("")
selected_row = input("SELECT A ROW: ")
print("")
selected_column = input("SELECT A COLUMN: ")
print("")
print("YOU SELECTED ROW "+selected_row+" AND COLUMN "+selected_column)
print("")